# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\stone\PycharmProjects\Face3\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 111)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.img_path = QtWidgets.QLineEdit(Form)
        self.img_path.setObjectName("img_path")
        self.gridLayout.addWidget(self.img_path, 0, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(Form)
        self.browse.setObjectName("browse")
        self.gridLayout.addWidget(self.browse, 0, 1, 1, 1)
        self.confirm = QtWidgets.QPushButton(Form)
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 0, 2, 1, 1)
        self.img_name = QtWidgets.QLineEdit(Form)
        self.img_name.setObjectName("img_name")
        self.gridLayout.addWidget(self.img_name, 1, 0, 1, 1)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.img_path.setPlaceholderText(_translate("Form", "请选择图片路径"))
        self.browse.setText(_translate("Form", "选择路径"))
        self.confirm.setText(_translate("Form", "确定"))
        self.img_name.setPlaceholderText(_translate("Form", "请输入姓名"))
        self.cancel.setText(_translate("Form", "取消"))
